### ISSUE TITLE
Is one kinect better than 360 kinect?

### ISSUE THREAD

**Issue by guyman70718** [sharkyh20/KinectToVR#14]
I want to buy a kinect for this purpose, but I don't know which kinect is better for this. The 360 kinect is much cheaper than a one kinect but is it maybe worth the extra money?

**Comment by sharkyh20** [comment]
The Kinect for Xbox One is much better tracking than the 360 - I'd say it's worth the extra money if you can either get the adapter for $20-30 premade, or you know how to solder it. (It was really easy though, first time I ever soldered anything was for my kinect).

 If it costs much more than that, or you don't have enough USB ports (or if they're unsupported https://stackoverflow.com/questions/30846191/usb3-controller-kinect-2 and https://social.msdn.microsoft.com/Forums/en-US/bb379e8b-4258-40d6-92e4-56dd95d7b0bb/confirmed-list-of-usb-30-pcie-cardslaptopsconfigurations-which-work-for-kinect-v2-during?forum=kinectv2sdk ) I would say it wouldn't be worth it.

There is also the possibility to use PSMoves for tracking, which is much more reliable and closer to Vive trackers than the kinect ever can be - but the kinect is still currently unsupported for it. If you end up going down this route, ask for help on the K2VR discord - I'll be able to reply quicker/ other people can share their experience with you too. 

The PSEyes are very cheap to fairly cheap depending on where you live, but you do need 3-4 for a good 360 degree tracking experience - and 3 move controllers. (You can get by on two controllers, as I have a virtual hip feature, but having an actual hip is always better.)
