### ISSUE TITLE
Kinect position and rotation

### ISSUE THREAD

**Issue by mcpedro99** [sharkyh20/KinectToVR#2]
got everything working, actually even went ahead a step and hopped in vrchat and I can actually see the little white balls, problem is, on the adjusting the kinect position step, it simply wont move, I tried 3 different versions , 5.2, 5.5 and 5.6 and none of them I could get it to move or rotate, restarted my computer 4 times, checked to see if I have both visual studio, checked different boxes in different orders and nothing I do seen to make the arrow move, and it actually got to the point were I restarted the app so much that now the green arrow and the trackers don't even show up anymore

**Comment by mcpedro99** [comment]
Actually I'm not in the SteamVR Beta, and even disabled the stupid Steam Home, but since you closed the Issue so quick I see you are not very interested in helping so I guess I will input the numbers manually in the config file

**Comment by sharkyh20** [comment]
Apologies, but that's what the issue has been so far, my bad. The discord is generally active and I can usually help better there - but I'm in classes around this time, so I may not be able to reply immediately

**Comment by mcpedro99** [comment]
So, the issue persists, no luck in making the position work, I was afraid it could be the Visual Studio being broken or something (idk I'm just trying anything at this point) and uninstalled the versions I had and installed it again but still get the same problem. Again, I am inputting the numbers manually in the KinectToVR.cfg and adjusting the rotation by moving my kinect (rotating it just the slightest make a huge difference inside the 3D space holy moly) and been using it this way, good free software btw congrats on that, but the problem is still there

**Comment by sharkyh20** [comment]
What VR Headset are you using, and are you using VR controllers or a gamepad? Also, the rotation numbers in the config file are in radians (You can convert degrees to their radian value by multiplying by pi, and dividing by 180. E.g. 90 degrees = 90pi/180 = 1.5708 rads). Instead of physically moving the kinect, you can change it in the config file until 
we get the calibration with thumbsticks to work,

**Comment by mcpedro99** [comment]
Oh so that is why using even small numbers had such a huge difference in the rotation. I'm using the Oculus Rift and the Rift controllers, bought then 2 weeks ago, the Kinect is the 360, 2 cameras and good visibility and space ( almost 10 ft).
The only thing out of the normal is the visual studio, Microsoft site being super useful, it doesn't show the version you gave us to install in the [front page](https://www.microsoft.com/en-us/download/details.aspx?id=14632) , but I already had both 2010 and 2017 x64 installed, the problem is, [I have newer versions](http://prntscr.com/jv18x4), the 2010 I have installed is [this one](http://prntscr.com/jv1aww) and the 2017 is [this one](http://prntscr.com/jv1bon)
Do you believe there is a chance that the newer versions are to blame here? that is the only different thing in the hole setup here

**Comment by sharkyh20** [comment]
That might be the problem. You could try to uninstall those, and reinstall with the previous version, but unless Microsoft royally screwed up that set of distributables, they're designed to be backwards compatible. However, here's a couple other things to try too:
Running Steam and K2VR as admin
Reinstalling the InputEmulator
Verify integrity of SteamVR
Deleting the KinectToVR.cfg file in the folder

Also, make sure the SteamVR menu isn't open, as it freezes the trackers in place.
You aren't clicking down on the trigger in the void after enabling the checkbox?
Really odd that this is happening with the Rift, only been the MR headsets that have had this problem.

**Comment by mcpedro99** [comment]
Aaaanndd you were right, kinda unexpected, would never thought that the version of the driver would affect it so much, but yeah by uninstalling the recent versions of visual studios and installing the ones provided on the front page everything works correctly
