### ISSUE TITLE
New SteamVR broke KinectToVr

### ISSUE THREAD

**Issue by Faiye** [sharkyh20/KinectToVR#4]
Hello, I was wondering if you can fix the issue with kinect to vr? Apparently the new  steamvr update broke this, and kinect is taking over input or something. Making the controllers useless when kinect to vr is on.

**Comment by sharkyh20** [comment]
The new update 0.5.7 fixes this - you can find it on the releases page here: https://github.com/sharkyh20/KinectToVR/releases/tag/0.5.7
