### ISSUE TITLE
wii controller

### ISSUE THREAD

**Issue by rafajjs** [sharkyh20/KinectToVR#43]
can i have my hand(positional tracking) with a wii controller and the 360 kinect?

**Comment by KemyszPL** [comment]
Would like to know the same with Joy-Cons. Looking through other issues, unfortunately it appears no.

**Comment by AuroraNemoia** [comment]
this isn't the main repository for development anymore. you should look towards https://github.com/kinecttovr/kinecttovr

The current scope of the project is still limited to lower body tracking with kinect skeleton tracking or psmoveservice only. There's various factors as to why we haven't branched out, like us wanting to give the best experience for the specific niche we're targeting.

If you absolutely want an opensource solution, I would check out https://github.com/okawo80085/hobo_vr though it isn't very much user-friendly.

Also, this post is really old, necro much? _should probably add a stale bot to this_
