### ISSUE TITLE
Unable to move arrow to Windows Mixed Reality

### ISSUE THREAD

**Issue by Astyui** [sharkyh20/KinectToVR#5]
Hello sharkyh20, I'm trying KinectToVR on Windows Mixed Reality
I can't move the Kinect arrows from any version of KinectToVR by TouchPad on Windows Mixed Reality Motion Controller.
Are there other methods of calibration?
Do you have an idea to work calibration by Thumbstick or Buttons on the TouchPad?

**Comment by sharkyh20** [comment]
Hey, it seems like only WMR is affected by this bug. Latest patch was a bandaid fix, and it seems that for the Rift and Vive it works just fine, but for WMR I have to fully implement the bindings system.

Others have documented this behaviour here:
https://github.com/ValveSoftware/openvr/issues/875

This may take a little while for me to figure out, as I need to go through all the documentation for the new input system. *Hopefully* within the next few days, but I also can't verify it without public testing, as I don't have a WMR headset.

**Comment by wiggle1000** [comment]
Godspeed

**Comment by sharkyh20** [comment]
Try the latest experimental build here:
https://github.com/sharkyh20/KinectToVR/releases/tag/0.5.9e

There's accompanying documentation/images on the discord, and I can provide support a lot quicker, too.
